vars:
  - online_fa_io:
      results_file: experiments/data/online_fa_results.parquet
      analysis_dir: experiments/data/online_fa_analysis
  - uci_datasets_io:
      datasets_dir: experiments/data/uci_datasets
  - linear_regression_vi_io:
      results_dir: experiments/data/linear_regression_vi_results
  - neural_net_predictions_io:
      results_dir: experiments/data/neural_net_predictions_results
  - slang_datasets_io:
      datasets_dir: experiments/data/slang_datasets

stages:
  online_fa:
    cmd: python experiments/online_fa.py
      --results-output-path ${online_fa_io.results_file}
    deps:
      - experiments/online_fa.py
      - swafa/fa.py
      - experiments/utils/factory.py
      - experiments/utils/metrics.py
    params:
      - online_fa.gradient_optimiser
      - online_fa.gradient_optimiser_kwargs
      - online_fa.gradient_warm_up_time_steps
      - online_fa.em_warm_up_time_steps
      - online_fa.experiments
      - online_fa.n_trials
    outs:
      - ${online_fa_io.results_file}

  online_fa_analysis:
    cmd: python experiments/online_fa_analysis.py
      --results-input-path ${online_fa_io.results_file}
      --analysis-output-dir ${online_fa_io.analysis_dir}
    deps:
      - experiments/online_fa_analysis.py
      - experiments/data/online_fa_results.parquet
    params:
      - online_fa_analysis.min_samples
    outs:
      - ${online_fa_io.analysis_dir}

  download_uci_datasets:
    cmd: python experiments/uci_datasets.py
      --boston-housing-output-path ${uci_datasets_io.datasets_dir}/boston_housing.parquet
      --yacht-hydrodynamics-output-path ${uci_datasets_io.datasets_dir}/yacht_hydrodynamics.parquet
      --concrete-strength-output-path ${uci_datasets_io.datasets_dir}/concrete_strength.parquet
      --energy-efficiency-output-path ${uci_datasets_io.datasets_dir}/energy_efficiency.parquet
    deps:
      - experiments/uci_datasets.py
    outs:
      - ${uci_datasets_io.datasets_dir}

  linear_regression_vi:
    foreach: ${linear_regression_vi.datasets} # from params.yaml
    do:
      cmd: python experiments/linear_regression_vi.py
        --dataset-label ${key}
        --dataset-input-path ${uci_datasets_io.datasets_dir}/${key}.parquet
        --results-output-dir ${linear_regression_vi_io.results_dir}/${key}
      deps:
        - experiments/linear_regression_vi.py
        - swafa/fa.py
        - swafa/models.py
        - swafa/callbacks.py
        - experiments/linear_regression_posterior.py
        - experiments/utils/factory.py
        - experiments/data/uci_datasets
      params:
        - linear_regression_vi.testing
        - linear_regression_vi.datasets.${key}
      outs:
        - ${linear_regression_vi_io.results_dir}/${key}

  neural_net_predictions:
    foreach: ${neural_net_predictions.datasets} # from params.yaml
    do:
      cmd: python experiments/neural_net_predictions.py
        --dataset-label ${key}
        --dataset-input-path ${uci_datasets_io.datasets_dir}/${key}.parquet
        --results-output-dir ${neural_net_predictions_io.results_dir}/${key}
      deps:
        - experiments/neural_net_predictions.py
        - swafa/fa.py
        - swafa/models.py
        - swafa/callbacks.py
        - swafa/utils.py
        - experiments/utils/factory.py
        - experiments/data/uci_datasets
      params:
        - neural_net_predictions.n_cv_folds
        - neural_net_predictions.n_hyperparameter_trials
        - neural_net_predictions.hidden_dims
        - neural_net_predictions.hidden_activation_fn
        - neural_net_predictions.data_split_random_seed
        - neural_net_predictions.test
        - neural_net_predictions.n_train_test_splits
        - neural_net_predictions.train_fraction
        - neural_net_predictions.datasets.${key}
      outs:
        - ${neural_net_predictions_io.results_dir}/${key}

  download_slang_datasets:
    cmd: python experiments/slang_datasets.py
      --datasets-output-dir ${slang_datasets_io.datasets_dir}
    deps:
      - experiments/slang_datasets.py
    outs:
      - ${slang_datasets_io.datasets_dir}
